# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ba6f614ffc823af1eac267a93d92f5a8c0fbf1858012be41faf4872373cace6277e3847e95f56fb3d2b5327d4e63c2d54be3307a14d17425d97c5beee1f2ef2

test:
  secret_key_base: 0be8540413beb1f6c6698cbfcf6af67a93583762a8dbce2d85a55c66f82298f076d9ae21b36eddc013ff6ad8b8b2368e7f3d987c0cce646adfb7ed72e22b855b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
