# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 757d0a28966422e0b4889170ebe708f47183ca3b8e18bc08de093ec6c3a9cc909872a993116d6a8f9a82d5a8cdbccb6bc3c295c50d4aaa826158aeeade1296a2

test:
  secret_key_base: e3435fcae4173372c477e6b2a59950e5be96ff391e07785478334b6fc686e91403d0b9f2828f03df429f6a08b3efc1698541f121f4b45f0cb351af982e53f039

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
